/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const HabitCategory = IDL.Variant({
  'exercise' : IDL.Null,
  'sleep' : IDL.Null,
  'study' : IDL.Null,
});
export const HabitLogEntry = IDL.Record({
  'date' : IDL.Int,
  'timestamp' : IDL.Int,
  'quantity' : IDL.Float64,
  'category' : HabitCategory,
});

export const idlService = IDL.Service({
  'createLog' : IDL.Func([HabitCategory, IDL.Float64, IDL.Int], [], []),
  'getAllLogs' : IDL.Func([], [IDL.Vec(HabitLogEntry)], ['query']),
  'getLogsByCategory' : IDL.Func(
      [HabitCategory],
      [IDL.Vec(HabitLogEntry)],
      ['query'],
    ),
  'getLogsByDateRange' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(HabitLogEntry)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const HabitCategory = IDL.Variant({
    'exercise' : IDL.Null,
    'sleep' : IDL.Null,
    'study' : IDL.Null,
  });
  const HabitLogEntry = IDL.Record({
    'date' : IDL.Int,
    'timestamp' : IDL.Int,
    'quantity' : IDL.Float64,
    'category' : HabitCategory,
  });
  
  return IDL.Service({
    'createLog' : IDL.Func([HabitCategory, IDL.Float64, IDL.Int], [], []),
    'getAllLogs' : IDL.Func([], [IDL.Vec(HabitLogEntry)], ['query']),
    'getLogsByCategory' : IDL.Func(
        [HabitCategory],
        [IDL.Vec(HabitLogEntry)],
        ['query'],
      ),
    'getLogsByDateRange' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(HabitLogEntry)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };